# Generated by Django 5.1 on 2024-08-29 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardWord',
            fields=[
                ('id', models.CharField(default='None', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('writing', models.CharField(blank=True, max_length=100, null=True)),
                ('meaning', models.CharField(blank=True, max_length=100, null=True)),
                ('furigana', models.CharField(blank=True, max_length=100, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.flashcardlist')),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardKanji',
            fields=[
                ('id', models.CharField(default='None', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('writing', models.CharField(blank=True, max_length=100, null=True)),
                ('hanviet', models.CharField(blank=True, max_length=100, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.flashcardword')),
            ],
        ),
    ]
