# Generated by Django 5.1 on 2024-08-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_alter_flashcardkanji_id_alter_flashcardword_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardkanji',
            name='id',
            field=models.CharField(default='None', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='flashcardkanji',
            name='word',
        ),
        migrations.AlterField(
            model_name='flashcardword',
            name='id',
            field=models.CharField(default='None', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='flashcardword',
            name='list',
        ),
        migrations.AddField(
            model_name='flashcardkanji',
            name='word',
            field=models.ManyToManyField(related_name='kanjis', to='flashcard.flashcardword'),
        ),
        migrations.AddField(
            model_name='flashcardword',
            name='list',
            field=models.ManyToManyField(related_name='words', to='flashcard.flashcardlist'),
        ),
    ]
