# Generated by Django 5.1 on 2024-08-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_alter_flashcardkanji_id_remove_flashcardkanji_word_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardlist',
            old_name='list_id',
            new_name='id',
        ),
    ]
