# Generated by Django 5.1.1 on 2024-09-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_remove_flashcardkanji_word_flashcardkanjilist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardword',
            name='writing',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
