# Generated by Django 5.1.1 on 2024-09-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0007_alter_flashcardword_writing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardkanji',
            name='hanviet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flashcardkanji',
            name='writing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flashcardlist',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flashcardword',
            name='furigana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flashcardword',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcardword',
            name='writing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
