# Generated by Django 5.1 on 2024-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanjimeaning',
            name='example',
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='examples',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='kanjimeaning',
            name='example_kun',
        ),
        migrations.RemoveField(
            model_name='kanjimeaning',
            name='example_on',
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='example_kun',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='example_on',
            field=models.JSONField(default=list),
        ),
    ]
