# Generated by Django 5.1 on 2024-08-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_remove_kanjimeaning_example_kanjimeaning_examples_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanjimeaning',
            name='example_kun',
        ),
        migrations.RemoveField(
            model_name='kanjimeaning',
            name='example_on',
        ),
        migrations.RemoveField(
            model_name='kanjimeaning',
            name='examples',
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='mean',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='transcription',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='SearchField',
        ),
    ]
