# Generated by Django 5.1 on 2024-08-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_remove_maziiwordexamplereturntype_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanjimeaning',
            name='h',
        ),
        migrations.RemoveField(
            model_name='kanjimeaning',
            name='w',
        ),
        migrations.RemoveField(
            model_name='maziiwordexamplereturntype',
            name='example_kun',
        ),
        migrations.RemoveField(
            model_name='maziiwordexamplereturntype',
            name='example_on',
        ),
        migrations.RemoveField(
            model_name='maziiwordexamplereturntype',
            name='examples',
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='example_kun',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='example_on',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='examples',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='maziiwordexamplereturntype',
            name='results',
            field=models.ManyToManyField(to='dictionary.wordexample'),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='mean',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='transcription',
            field=models.TextField(),
        ),
    ]
