# Generated by Django 5.1 on 2024-08-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_remove_kanjimeaning_h_remove_kanjimeaning_w_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Kanji',
        ),
        migrations.RemoveField(
            model_name='maziiwordexamplereturntype',
            name='results',
        ),
        migrations.RemoveField(
            model_name='maziiwordkanjireturntype',
            name='results',
        ),
        migrations.RemoveField(
            model_name='maziiwordmeaningreturntype',
            name='data',
        ),
        migrations.RemoveField(
            model_name='maziiwordtranslate',
            name='means',
        ),
        migrations.RemoveField(
            model_name='onyomiexample',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='wordmeaning',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='wordmeaning',
            name='mean',
        ),
        migrations.AddField(
            model_name='kanjimeaning',
            name='level',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='wordmeaning',
            name='means',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='wordmeaning',
            name='mobileId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordmeaning',
            name='phonetic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wordmeaning',
            name='short_mean',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wordmeaning',
            name='word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kanjimeaning',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kanjimeaning',
            name='example_kun',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='kanjimeaning',
            name='example_on',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='kanjimeaning',
            name='examples',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='kanjimeaning',
            name='kanji',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kanjimeaning',
            name='kun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kanjimeaning',
            name='mean',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kanjimeaning',
            name='mobileId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kanjimeaning',
            name='on',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kanjimeaning',
            name='stroke_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overallexample',
            name='h',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='overallexample',
            name='m',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='overallexample',
            name='p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='overallexample',
            name='w',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='mean',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='KunyomiExample',
        ),
        migrations.DeleteModel(
            name='MaziiWordExampleReturnType',
        ),
        migrations.DeleteModel(
            name='MaziiWordKanjiReturnType',
        ),
        migrations.DeleteModel(
            name='MaziiWordMeaningReturnType',
        ),
        migrations.DeleteModel(
            name='MaziiWordTranslate',
        ),
        migrations.DeleteModel(
            name='OnyomiExample',
        ),
    ]
