# Generated by Django 5.1 on 2024-08-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_alter_example_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractKanjiList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardKanji',
            fields=[
                ('kanji_id', models.ForeignKey(db_column='kanji_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dictionary.extractkanjilist')),
                ('writing', models.CharField(blank=True, max_length=100, null=True)),
                ('hanviet', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardWord_list',
            fields=[
                ('list_id', models.ForeignKey(db_column='list_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dictionary.flashcardlist')),
                ('word_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardWord',
            fields=[
                ('word_id', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dictionary.flashcardword_list')),
                ('writing', models.CharField(blank=True, max_length=100, null=True)),
                ('meaning', models.CharField(blank=True, max_length=100, null=True)),
                ('furigana', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='extractkanjilist',
            name='word_id',
            field=models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, to='dictionary.flashcardword'),
        ),
    ]
