# Generated by Django 5.1 on 2024-08-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_alter_extractkanjilist_word_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractkanjilist',
            name='word_id',
            field=models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, to='dictionary.flashcardword'),
        ),
        migrations.AlterField(
            model_name='flashcardkanji',
            name='kanji_id',
            field=models.ForeignKey(db_column='kanji_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dictionary.extractkanjilist'),
        ),
        migrations.AlterField(
            model_name='flashcardword',
            name='word_id',
            field=models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dictionary.flashcardword_list'),
        ),
        migrations.AlterField(
            model_name='flashcardword_list',
            name='list_id',
            field=models.ForeignKey(db_column='list_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dictionary.flashcardlist'),
        ),
    ]
