# Generated by Django 5.1 on 2024-08-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_remove_flashcardkanji_kanji_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardword',
            old_name='word_id',
            new_name='id',
        ),
    ]
