# Generated by Django 5.1 on 2024-08-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_rename_word_id_flashcardword_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardlist',
            name='word_list',
        ),
        migrations.RemoveField(
            model_name='flashcardword',
            name='kanji_list',
        ),
        migrations.AddField(
            model_name='flashcardkanji',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.flashcardword'),
        ),
        migrations.AddField(
            model_name='flashcardword',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.flashcardlist'),
        ),
    ]
