# Generated by Django 5.1 on 2024-08-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_remove_flashcardlist_word_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardword',
            name='list',
        ),
        migrations.DeleteModel(
            name='FlashcardKanji',
        ),
        migrations.DeleteModel(
            name='FlashcardList',
        ),
        migrations.DeleteModel(
            name='FlashcardWord',
        ),
    ]
